language: cpp
os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode7.1
git:
  submodules: false
addons:
  ssh_known_hosts:
    - github.com
  apt:
    packages:
      - premake4
      - libfreetype6-dev
      - libevent-dev
      - libsqlite3-dev
      - libirrlicht-dev
      - liblua5.2-dev
      - libgl1-mesa-dev
      - libglu-dev
before_install:
  - openssl aes-256-cbc -K $encrypted_c268b785a48e_key -iv $encrypted_c268b785a48e_iv -in ssh-key.enc -out $HOME/.ssh/id_ecdsa -d
  - chmod 600 $HOME/.ssh/id_ecdsa
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ssh -v git@github.com; fi
  - git submodule update --init --recursive
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install premake freetype libevent sqlite irrlicht lua; fi
script:
  - premake4 gmake
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cat /etc/ld.so.conf.d/*; sed -i 's/-llua/-llua5.2/g' ygopro.make; fi
  - make config=release
branches:
  only:
    - master
