language: cpp
os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode8
git:
  submodules: false
addons:
  ssh_known_hosts:
    - github.com
  apt:
    packages:
      - premake4
      - libfreetype6-dev
      - libevent-dev
      - libsqlite3-dev
      - libirrlicht-dev
      - liblua5.2-dev
      - libgl1-mesa-dev
      - libglu-dev
before_install:
  - openssl aes-256-cbc -K $encrypted_c268b785a48e_key -iv $encrypted_c268b785a48e_iv -in ssh-key.enc -out $HOME/.ssh/id_ecdsa -d
  - chmod 600 $HOME/.ssh/id_ecdsa
  - git submodule update --init --recursive
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install premake freetype libevent sqlite irrlicht lua; fi
script:
  - premake4 gmake
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sed -i 's/-llua/-llua5.2/g' ygopro.make; fi
  - make config=release
  - cd ..
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv bin/release/ygopro ./; strip ygopro; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mv bin/release/ygopro.app ./ ./; strip ygopro.app/Contents/MacOS/ygopro; fi
  - wget https://mycard.moe/ygopro/cards.cdb
  - mkdir -p pics; wget -O - https://github.com/mycard/ygopro-images/archive/zh-CN.tar.gz | tar --strip-components=1 -C pics -zxf -
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then XZ_OPT=-9e tar -Jcf ygopro.tar.xz ygopro LICENSE README.md lflist.conf script strings.conf system.conf textures cards.cdb pics; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then XZ_OPT=-9e tar -Jcf ygopro.tar.xz ygopro.app LICENSE README.md lflist.conf script strings.conf system.conf textures cards.cdb pics; fi
deploy:
  provider: releases
  file: "ygopro.tar.xz"
  api_key:
      secure: "hJ0p7PrsahA+e8szAnepJC+D02cobtFWZtC2qH2Aljr4RGP0Mi/4p7k9m+Ob27NBaGA1wg0B6W+SNX3uEAUkr5upS+/VRhb0i34zkFiYw30KpufXjQ0TiWGJfozV97T4UzMFtl+dYh/WLMO+QTwQK9EE0FLwTWWn6aXrNPDZYQA="
  skip_cleanup: true
  on:
    tags: true
branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/
