language: c

os:
  - linux
  - osx

git:
  submodules: false

before_install:
  - echo SSH_KEY | ssh-add -
  - git submodule update --init --recursive
  - brew update
  - brew install premake

install: 
  - premake4 gmake
  - cd build
  - make config=release

branches:
  only:
  - master
