language: c

os:
  - linux
  - osx

before_install:
  - echo SSH_KEY | ssh-add -
  - brew update
  - brew install premake

install: 
  - premake4 gmake
  - cd build
  - make config=release

branches:
  only:
  - master
