version: '{build}'
install:
  # submodules
  - git submodule update --init --recursive
  
  # environment and system dependency
  - curl --location --retry 5 --output 'premake-5.0.0-alpha9-windows.zip' 'https://github.com/premake/premake-core/releases/download/v5.0.0-alpha9/premake-5.0.0-alpha9-windows.zip'
  - 7z x premake-5.0.0-alpha9-windows.zip
  
  - curl --location --retry 5 'https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz' | tar zxf -
  - move libevent-2.0.22-stable event
  - xcopy /E event\WIN32-Code event\include
  
  - curl --location --retry 5 'http://downloads.sourceforge.net/freetype/freetype-2.7.tar.bz2' | tar jxf -
  - move freetype-2.7 freetype
  
  - curl --location --retry 5 --output 'irrlicht-1.8.4.zip' 'http://downloads.sourceforge.net/irrlicht/irrlicht-1.8.4.zip'
  - 7z x irrlicht-1.8.4.zip
  - md irrlicht
  - move irrlicht-1.8.4\source\Irrlicht irrlicht\src
  - move irrlicht-1.8.4\include irrlicht\include
  
  - curl --location --retry 5 'https://www.lua.org/ftp/lua-5.2.4.tar.gz' | tar zxf -
  - move lua-5.2.4\src lua
  
  - curl --location --retry 5 --output 'sqlite-amalgamation-3140200.zip' 'https://www.sqlite.org/2016/sqlite-amalgamation-3140200.zip'
  - 7z x sqlite-amalgamation-3140200.zip
  - move sqlite-amalgamation-3140200 sqlite3
  
  # let premake happy
  - xcopy /E premake\* .
  
  # patch irrlicht
  - patch -p0 < irrlicht\irrlicht.patch
  
  # premake
  - premake5 vs2015
  
configuration: Release
build: 
    project: build/ygo.sln
    parallel: true
after_build:
  - ps: move bin\release\ygopro.exe .
  - curl --location --retry 5 'https://github.com/mycard/ygopro-database/archive/master.tar.gz' | tar --strip-components=1 -zxf - ygopro-database-master/locales
  - cp locales/zh-CN/* .
  - 7z a ygopro-lite-%APPVEYOR_REPO_TAG_NAME%-win32.7z ygopro.exe LICENSE README.md lflist.conf script strings.conf system.conf textures deck cards.cdb locales
  - mkdir pics
  - curl --location --retry 5 --output 'ygopro-images-zh-CN.zip' https://github.com/mycard/ygopro-images/releases/download/latest/ygopro-images-zh-CN.zip
  - unzip -q -d pics ygopro-images-zh-CN.zip
  - 7z a ygopro-%APPVEYOR_REPO_TAG_NAME%-win32.7z ygopro.exe LICENSE README.md lflist.conf script strings.conf system.conf textures deck cards.cdb pics locales
artifacts:
  - path: ygopro-lite-$(APPVEYOR_REPO_TAG_NAME)-win32.7z
    name: ygopro-lite
  - path: ygopro-$(APPVEYOR_REPO_TAG_NAME)-win32.7z
    name: ygopro
deploy:
  description: 'Automatic build'
  provider: GitHub
  auth_token:
    secure: itZ9Z1dxEpfPJLdTs/PiY98pVZ3GCLNWfid7eAu7SL88Jl9AIrf/3rviKFEbsnoY # your encrypted token from GitHub
  on:
    appveyor_repo_tag: true        # deploy on tag push only
branches:
  only:
    - master
    - /\d+\..+/
