environment:
  priv_key:
      secure: ek1AH0N8/KF6VoildmkHnu4TY1yBZcptm20AesAOanRSSGLFqkXeRxL80mHSXtiVY8ggtQNsEQR4M69gCiw1OPVWz4OAN6Vg6id6kho9GqYxWCdADbmffSNPB5leksRGjGmkAF99WHiOIZrLRUb6Bia91Fe5+SngPhI01GDDUZA2urv9x50uBBhc+kvV0bv7J5TeXDGr7tfZ3J2aL/3tf/WPqBkqjWlGAj99HTWpkIiQgwaBHoyBvEFD0uHa1BdSmI7PySGabbx4/4zqyGkO38Ce7t/Ntu/dgedzVxlXYfuiXDI8caAPZSVsJ9E2S3VKesZJzHtV9KM/8Xq0RFPythdC/qTvd2e3IAZGudZpgbUHGAHLJnCzn189Zm+Qle8CbbVuPNDcf1B/G/XwEU2MsDXGkF/kFxdeqbHgjzneyns=
version: '{build}'
install:
  # ssh key and submodules
  - ps: $fileContent = "-----BEGIN EC PRIVATE KEY-----`n"
  - ps: $fileContent += $env:priv_key.Replace(' ', "`n")
  - ps: $fileContent += "`n-----END EC PRIVATE KEY-----`n"
  - ps: Set-Content c:\users\appveyor\.ssh\id_ecdsa $fileContent
  - git submodule update --init --recursive

  # environment and system dependency
  - ps: Start-FileDownload https://github.com/premake/premake-core/releases/download/v5.0.0-alpha9/premake-5.0.0-alpha9-windows.zip premake.zip
  - 7z x premake.zip
  - ps: Start-FileDownload http://download.savannah.gnu.org/releases/freetype/freetype-2.7.tar.gz freetype.tar.gz
  - 7z x freetype.tar.gz

after_build:
artifacts:
  - path: ygopro-images
    name: ygopro-images-zh-CN
    type: 7z
deploy:
  release: latest
  description: 'Automatic build'
  provider: GitHub
  auth_token:
    secure: itZ9Z1dxEpfPJLdTs/PiY98pVZ3GCLNWfid7eAu7SL88Jl9AIrf/3rviKFEbsnoY # your encrypted token from GitHub
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    #appveyor_repo_tag: true        # deploy on tag push only

#build: off